# fly.toml app configuration file generated for banner-generator on 2025-07-28T23:00:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'banner-generator'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  BANNER_CACHE_TTL = '6h'
  FONT_PATH = '/app/fonts'
  GIN_MODE = 'release'
  GITHUB_REPO_CACHE_TTL = '24h'
  GITHUB_USER_CACHE_TTL = '24h'
  PORT = '8080'
  TEMPLATES_PATH = '/app/templates'

[processes]
  app = './banner-api'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
